Repository AnnaIsah/SAP007-social-network, pull requests merged in 2022-04, with the labels that each got.

#35 Fix/csstimelinepostmobile
  src/components/timelinepost.js
  src/components/timelineposts.css
  src/index.html
  src/pages/feed/feed.css
  src/style/reset.css
Labels: fix

#36 feat: like post
  src/components/timelinepost.js
  src/pages/feed/feed.js
  src/pages/feed/firestore-functions.js
  src/style/reset.css
Labels: feat

#37 fix: like
  src/components/timelinepost.js
Labels: bug, fix

#38 feat: CSS comment
  src/components/timelinepost.js
  src/components/timelineposts.css
Labels: feat
